// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEpOoeFbcY0bZp_MNmIz39vGpsdABEfp0',
    appId: '1:185498054079:android:8e42fe1c55c2ec0bda450a',
    messagingSenderId: '185498054079',
    projectId: 'db-insta-59421',
    storageBucket: 'db-insta-59421.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2P6gQnD0eujyTRmKfNuzikA3EpysPBk',
    appId: '1:185498054079:ios:5e78c62b9cedbe2cda450a',
    messagingSenderId: '185498054079',
    projectId: 'db-insta-59421',
    storageBucket: 'db-insta-59421.appspot.com',
    iosClientId: '185498054079-u4lukousj7kpj9raajii10bug7jn93mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2P6gQnD0eujyTRmKfNuzikA3EpysPBk',
    appId: '1:185498054079:ios:5e78c62b9cedbe2cda450a',
    messagingSenderId: '185498054079',
    projectId: 'db-insta-59421',
    storageBucket: 'db-insta-59421.appspot.com',
    iosClientId: '185498054079-u4lukousj7kpj9raajii10bug7jn93mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApps',
  );
}
